### ISSUE TITLE
Fix the timezone to be GMT?

### ISSUE THREAD

**Issue by Quirksmode** [tomgrohl/jCountdown#16]
When I run a countdown, the timezone of the computer clock affects the countdown date. Is there a way to force the countdown to always stay fixed to GMT. E.g. if someone in Australia views the countdown they will see the same countdown time as someone in the UK.

    $("#countdown").countdown({
         "date" : "August 14, 2015 19:45:00",
     });

**Comment by websiteduck** [comment]
You should be able to fix this by using a timestamp instead of a date string.

Using PHP it would be something like this:
```
$('#countdown').countdown({
    "date": new Date(<?=$datetime->getTimestamp()*1000?>)
});
```

If you are hardcoding the date into a javascript file, you can use a website like http://www.epochconverter.com to figure out what the timestamp should be, and then multiply it by 1000 (or use milliseconds version from website):
```
$('#countdown').countdown({
    "date": new Date(1475332994*1000)
});
```

**Comment by tomgrohl** [comment]
If you look at the the server demo in ```demo/servertime.php``` you will be able to achieve this.
